### PR TITLE
Dog dashboard mobile view

### PR DESCRIPTION
**Pull request by DanielChee**
## [FE] Dog dashboard mobile views

Issue Number(s): #164

What does this PR change and why?
This adds mobile view for dog dashboard, for Admin, Manager, and Volunteer (Card view).

### Checklist

- [yes] Requirements have been implemented
- [yes] Acceptance criteria is met
- [yes] Database schema [docs](https://www.notion.so/gtbitsofgood/Database-Schema-Docs-fd377ded10b54890b65fd99025488cee?pvs=4) have been updated or are not necessary
- [yes] Relevant reviewers (EM) have been assigned to this PR

### Critical Changes

- Database change / migration to run
- Environment config change
- Breaking API change

### Related PRs

PR Number(s): #141 #227 #226 #224 

### How To Test

scan the QR code to login through mobile view (test@gmail.com). navigate around dog dashboard.

### CODE REVIEW

**Review by afazio1 — CHANGES_REQUESTED** [review]
TABLES LOOK AMAZING!!

I noticed a small thing with the extended dropdown width not matching:
Screenshot 2024-03-24 at 9 26 30 AM

**Review by afazio1 — APPROVED** [review]
Looks great, well done!

**Review by laurenmcp — APPROVED** [review]
Awesome daniel!! Table is slaying 💅

**Comment by dograh** [comment]
This looks FANTASTIC!! The only minor change that I have is that it seems like the filters are center-aligned, so it sits at a different x position than the search bar and filters applied. Can we make it left-aligned so they all line up at the same place on the left? Other than that it looks perfect. You did a really good job!

**Pull request merged**
