### PR TITLE
Forgot Password

### LINKED ISSUE #193: [FE/BE] Implement forgot password
### Description
Users should be able to reset their password if needed. 

Implement the frontend and backend for resetting a password. 

**Forgot Password Flow** ->
- User clicks "Forgot Password" on `/login`
- User enters their email address in the modal
- If email exists in the db and `acceptedInvite: true`, then
	- generate a ResetCode
	- send an email to the user with the reset code
	- transition to modal where a user can enter their reset code
	- if the code is correct, allow them to enter a new password
	- Hash and save the new password to the user object
- else display an error message

**Reset code** -> Create a new model called `ResetCode`
- take reference from this schema: https://github.com/GTBitsOfGood/VolunTrack/blob/dev/server/mongodb/models/ResetCode/index.ts
- Reset codes are randomly generated 6 alphanumeric characters. Look into Node's builtin `crypto` library for generating random bytes. 
- Reset codes should expire after 15 minutes. Implement this by creating a MongoDB TTL index. Reach out to EM if you need help with this. 
**Email** -> Configure and set up [Brevo](https://developers.brevo.com/) Email API. Credentials are in the Bitwarden
- Use this for reference https://developers.brevo.com/docs/send-a-transactional-email#creating-your-api-request-using-brevo-api-clients
- Use an email template from Brevo. You can create a template on the website using the credentials on the bitwarden
- Update Bitwarden with environment variables like API keys

### Other notes
- Take reference from the VolunTrack project! https://github.com/GTBitsOfGood/VolunTrack/commit/0ae6b9482f4efbe0e07b09f56b6d8927e3bd3ae1 They use a different mail service, but the flow is similar.

### PR DESCRIPTION
**Pull request by parkerra**
## Forgot Password

Issue Number(s): #193 

The Forgot Password modal and backend functionality has been created to allow for the user to reset their password if forgotten after inputting a correct reset code sent to their email.

### Checklist

- [x] Requirements have been implemented
- [x] Acceptance criteria is met
- [x] Database schema [docs](https://www.notion.so/gtbitsofgood/Database-Schema-Docs-fd377ded10b54890b65fd99025488cee?pvs=4) have been updated or are not necessary
- [x] Relevant reviewers (EM) have been assigned to this PR

### Critical Changes

- New model created for `resetCode`, make sure to reset MongoDB if running into issues!

### Related PRs

PR Number(s): #193 

### How To Test

First log in as an Admin or Manager and invited yourself as a user using your real email address. Then Sign Up using that real email. Then log out again and click `Forgot Password?` on the Login screen. Make sure to test on mobile as well!

### CODE REVIEW

**Comment by laurenmcp** [comment]
I am getting an error in reset password that there is no account associated with my email address, but I can login just fine so I know that it exists. This error is happing with both my outlook email and Hemadri's gmail. I wonder if this has to do with us using a deploy preview vs running on local machine?

**Comment by parkerra** [comment]
> I am getting an error in reset password that there is no account associated with my email address, but I can login just fine so I know that it exists. This error is happing with both my outlook email and Hemadri's gmail. I wonder if this has to do with us using a deploy preview vs running on local machine?

It should work now! The problem was that the API key for the email service Brevo wasn't on Netlify yet so there was an error since the key couldn't be found, but it's been added now :D

**Comment by dograh** [comment]
design looks great!!

**Review by laurenmcp — APPROVED** [review]
awesome job parker! that was not an easy ticket AND you managed to do it without your laptop... SLAY!

**Review by afazio1 — APPROVED** [review]
giphy

**Pull request merged**
