### PR TITLE
Card Dog Table View for Volunteers/Recipients

### PR DESCRIPTION
**Pull request by qad114**
## Card Dog Table View for Volunteers/Recipients

Issue Number(s): #138

Displays a two-column card view when the user is not an Admin/Manager and has only volunteer/recipient associations with all dogs.

### Checklist

- [ ] Requirements have been implemented
- [ ] Acceptance criteria is met
- [ ] Database schema [docs](https://www.notion.so/gtbitsofgood/Database-Schema-Docs-fd377ded10b54890b65fd99025488cee?pvs=4) have been updated or are not necessary
- [ ] Relevant reviewers (EM) have been assigned to this PR

### How To Test

Test the following cases:
- When the user is an Admin/Manager: DogTable should show regardless of association
- When the user is a User and has an instructor/caregiver association with at least one dog: DogTable should show
- When the user is a User and has only volunteer/recipient associations with the dogs: CardDogTable should show

### CODE REVIEW

**Comment by qad114** [comment]
The code should be functional now. One issue is that the current loading screen is based on the table layout only (since there was only a DogTable before) so as of now, when you open the dashboard as a volunteer, the loading animation shows a table which then abruptly changes to a CardDogTable. Since there's no way to know the association until we receive the data, I feel like the only way around this would be to design a new universal loading screen that fits well with both the table and card views. I could also just disable the loading screen entirely for now. Any advice?

**Comment by dograh** [comment]
Awesome job with this ticket! I just have one minor change and then it is good to go. When there are a lot of recent log tags, the current functionality is that the card will extend in height to accommodate the tag. Can we keep the height size fixed and then implement the +1 overflow? Other than that everything looks great!

**Comment by dograh** [comment]
The +1 looks great! It still says +1 even if there is more than one tag in the overflow. It's also missing the tooltip that appears when you hover over the number to see the tag. 
Screenshot 2024-03-03 at 4 03 05 PM

**Comment by dograh** [comment]
Also forgot to mention that volunteers don't have the ability to add a dog. Can we remove that button?

**Comment by dograh** [comment]
design looks great!

**Review by afazio1 — APPROVED** [review]

**Pull request merged**
